# Candace Savonen Mar 2022

name: Testing ottr-reports
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:

  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check spelling
      id: check_spelling
      uses: ./
      with:
        check_type: spelling
        error_min: 3
        token: ${{ secrets.GH_PAT }}
        
    - name: Find outputs
      run: |
        echo ${{ steps.check_spelling.outputs.report_path }}
        cat ${{ steps.check_spelling.outputs.report_path }}
        echo ${{ steps.check_spelling.outputs.error_num}}
      shell: bash

  urls-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check URLs
      id: check_urls
      uses: ./
      with:
        check_type: urls
        error_min: 0
        token: ${{ secrets.GH_PAT }}

    - name: Find outputs
      run: |
        echo ${{ steps.check_urls.outputs.report_path }}
        cat ${{ steps.check_urls.outputs.report_path }}
        echo ${{ steps.check_urls.outputs.error_num}}
      shell: bash

  quiz-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4

    - name: Check quiz formatting
      id: quiz_format
      uses: ./
      with:
        check_type: quiz_format
        error_min: 0
        token: ${{ secrets.GH_PAT }}

    - name: Find outputs
      run: |
        echo ${{ steps.quiz_format.outputs.report_path }}
        cat ${{ steps.quiz_format.outputs.report_path }}
        echo ${{ steps.quiz_format.outputs.error_num}}
      shell: bash
